Added Rad debugListener.
npr/RAD-Android pull request #10
Opened 2018-11-20 15:06 UTC by bogdan-vld

2018-11-20 16:49 UTC, dmacra commented on rad/src/main/java/com/npr/rad/db/DaoMaster.java
> +            metadataDao.deleteNotIn(metadataIds);
I suggest to create a git Issue describing the topic and resolve in a separate PR.

2018-11-21 14:16 UTC, allenbaker requested changes
Can you please add `debugEnabled` to the `Configuration` class?

2018-11-21 16:15 UTC, allenbaker submitted a review, later dismissed

2018-11-21 16:25 UTC, dmacra approved these changes

2018-11-21 16:27 UTC, merged